// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: lpephejgwhyftboynbsk

class SupabaseConfig {
  static const String supabaseUrl = 'https://lpephejgwhyftboynbsk.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwZXBoZWpnd2h5ZnRib3luYnNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3MjA3NTksImV4cCI6MjA4MzI5Njc1OX0.-gpDeNEwovJVbs5hHr4MNJ_wdcNOf2NaZMRCrmIzJug';
}
